<?php

/**
 * @file
 * Collection of fields and utility functions for working with DC Metadata.
 */

define('ISLANDORA_DCTERMS_CONTRIBUTOR_FIELD', 'field_dcterms_contributor');
define('ISLANDORA_DCTERMS_COVERAGE_FIELD', 'field_dcterms_coverage');
define('ISLANDORA_DCTERMS_CREATOR_FIELD', 'field_dcterms_creator');
define('ISLANDORA_DCTERMS_DATE_FIELD', 'field_dcterms_date');
define('ISLANDORA_DCTERMS_DESCRIPTION_FIELD', 'field_dcterms_description');
define('ISLANDORA_DCTERMS_FORMAT_FIELD', 'field_dcterms_format');
define('ISLANDORA_DCTERMS_IDENTIFIER_FIELD', 'field_dcterms_identifier');
define('ISLANDORA_DCTERMS_LANGUAGE_FIELD', 'field_dcterms_language');
define('ISLANDORA_DCTERMS_PUBLISHER_FIELD', 'field_dcterms_publisher');
define('ISLANDORA_DCTERMS_RELATION_FIELD', 'field_dcterms_relation');
define('ISLANDORA_DCTERMS_RIGHTS_FIELD', 'field_dcterms_rights');
define('ISLANDORA_DCTERMS_SOURCE_FIELD', 'field_dcterms_source');
define('ISLANDORA_DCTERMS_SUBJECT_FIELD', 'field_dcterms_subject');
define('ISLANDORA_DCTERMS_TITLE_FIELD', 'field_dcterms_title');
define('ISLANDORA_DCTERMS_TYPE_FIELD', 'field_dcterms_type');
