<?php

/**
 * Implementation of hook_requried_fedora_objects()
 */
function islandora_newspaper_required_fedora_objects() {
  // array( 'path-to-foxml-file', 'pid', 'dsid', 'path-to-datastream-file', int dsversion, boolean required)
  $module_path = drupal_get_path('module', 'islandora_newspaper');
  return array(
    'islandora_newspaper' => array(
      'module' => 'islandora_newspaper',
      'title' => 'Islandora Newspaper',
      'objects' => array(
        array(
          //'foxml_file' => "$module_path/newspapers_issueCModel.xml",
          'pid' => 'newspapers:issueCModel',
          'dsid' => 'ISLANDORACM',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'datastream_file' => "$module_path/newspapers_issueCModel_islandoracm.xml",
          'dsversion' => 2,
        ),
        array(
          'foxml_file' => "$module_path/newspapers_pageCModel.xml",
          'pid' => 'newspapers:pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/newspapers_viewerSdep-issueCModel.xml",
          'pid' => 'newspapers:viewerSdep-issueCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/newspapers_viewerSdep-pageCModel.xml",
          'pid' => 'newspapers:viewerSdep-pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'pid' => 'newspapers:collection',
          'label' => 'Newspapers Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:demos',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/newspapers_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/Crystal_Clear_mimetype_document.png",
              'mimetype' => 'image/png',
            ),
          ),
        ),
      ),
    ),
  );
}