<?php

/**
 * @file
 * Islandora module for working with MODS Metadata.
 */

define('ISLANDORA_MODS_NAMESPACE', 'http://www.loc.gov/mods/v3/');
define('ISLANDORA_MODS_NAMESPACE_PREFIX', 'mods');
define('ISLANDORA_MODS_RDF_NAMESPACE', 'http://www.loc.gov/mods/modsrdf/v1#');
define('ISLANDORA_MODS_RDF_NAMESPACE_PREFIX', 'modsrdf');
define('ISLANDORA_MODS_FIELD', 'field_mods');

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_mods_rdf_namespaces() {
  return array(
    ISLANDORA_MODS_RDF_NAMESPACE_PREFIX => ISLANDORA_MODS_RDF_NAMESPACE,
  );
}
