<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 * Creates shared fields for content types using MODS metadata.
 */
function islandora_mods_install() {
  module_load_include('inc', 'islandora', 'include/fields');

  islandora_create_field(array(
                           'field_name' => ISLANDORA_MODS_FIELD,
                           'type' => 'xml_field_xml',
                         ));
}
