#!/bin/bash

HOME_DIR=$1
DOWNLOAD_DIR="$HOME_DIR/islandora/install/downloads"
FEDORA_VERSION=4.5.1
KARAF_VERSION=4.0.5
KARAF_DIR="/opt/karaf"
KARAF_CLIENT="$KARAF_DIR/bin/client"
KARAF_CONFIGS="$HOME_DIR/islandora/install/configs/karaf/"
CAMEL_VERSION=4.4.0
SOLR_VERSION=4.10.3
SOLR_HOME="/var/lib/tomcat7/solr"
BLAZEGRAPH_VERSION=1.5.1
DRUPAL_HOME="/var/www/html/drupal"
