#!/bin/bash

HOME_DIR=$1
DOWNLOAD_DIR="$HOME_DIR/islandora/install/downloads"
FEDORA_VERSION=4.7.0
KARAF_VERSION=4.0.5
KARAF_DIR="/opt/karaf"
KARAF_CLIENT="$KARAF_DIR/bin/client"
KARAF_CONFIGS="$HOME_DIR/islandora/install/configs/karaf/"
CAMEL_VERSION=4.4.0
SOLR_VERSION=6.2.1
BLAZEGRAPH_VERSION=2.1.4
DRUPAL_HOME="/var/www/html/drupal"
DRUSH_CMD="$DRUPAL_HOME/vendor/drush/drush/drush -r $DRUPAL_HOME/web"
DRUPAL_CMD="$DRUPAL_HOME/vendor/drupal/console/bin/drupal --root=$DRUPAL_HOME/web"
FITS_VERSION=1.0.3
FITS_WS_VERSION=1.1.3
MYSQL_USER=root
MYSQL_PASS=islandora
MYSQL_CONNECTOR_VERSION=6.0.4
