<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_install().
 *
 * Defines common fields for various bundles.
 */
function islandora_install() {
  $tn_field_name = 'field_tn';
  $tn_field = array(
    'field_name' => $tn_field_name,
    'type' => 'image',
  );
  field_create_field($tn_field);
}

/**
 * Implements hook_uninstall().
 */
function islandora_uninstall() {
  $tn_field_name = 'field_tn';
  field_delete_field($tn_field_name);
}
