<?php

/**
 * @file
 * This is the new Islandora Basic Image module.
 */

define('ISLANDORA_BASIC_IMAGE_BUNDLE', 'basic_image');
define('ISLANDORA_BASIC_IMAGE_MEDIUM_SIZE', 'medium_size');

/**
 * Function for using a form.
 *
 * @param string $node
 *   The Drupal node.
 * @param array $form_state
 *   The Drupal form state.
 */
function islandora_basic_image_form($node, array &$form_state) {
  return node_content_form($node, $form_state);
}
