<?php

/**
 * @file
 * Provides a service for adding medium size images to nodes.
 */

/**
 * Implements hook_permission().
 */
function islandora_medium_size_service_permission() {
  return array(
    'islandora medium size service create' => array(
      'title' => t('Add Medium Size'),
      'description' => t('Allows external sources to add medium size images to nodes.'),
    ),
  );
}

/**
 * Implements hook_services_resources().
 */
function islandora_medium_size_service_services_resources() {
  return array(
    'medium_size' => array(
      'create' => array(
        'help' => t('Adds a medium sized image to the node identified by UUID.'),
        'file' => array(
          'type' => 'inc',
          'module' => 'islandora_medium_size_service',
          'name' => 'include/islandora_medium_size_service',
        ),
        'callback' => 'islandora_medium_size_service_create',
        'access callback' => 'user_access',
        'access arguments' => array('islandora medium size service create'),
        'args' => array(
          array(
            'name' => 'args',
            'type' => 'array',
            'description' => t("JSON data containing arguments to add the medium sized image."),
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
    ),
  );
}
